/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Energy': '能源',
    ' Energy': ' 能源',
    ' Energy, ': ' 能源, ',
    'Gems': '宝石',
    ' Gems': ' 宝石',
    ' Gems, ': ' 宝石, ',
    'Gold': '黄金',
    ' Gold': ' 黄金',
    ' Gold, ': ' 黄金, ',
    'Ice': '冰',
    ' Ice': ' 冰',
    ' Ice, ': ' 冰, ',
    'Lava': '岩浆',
    ' Lava': ' 岩浆',
    ' Lava, ': ' 岩浆, ',
    'Silicon': '硅',
    ' Silicon': ' 硅',
    ' Silicon, ': ' 硅, ',
    'Silver': '银',
    ' Silver': ' 银',
    ' Silver, ': ' 银, ',
    'Wood': '木头',
    ' Wood': ' 木头',
    ' Wood, ': ' 木头, ',
    ' wood': ' 木头',
    ' wood, ': ' 木头, ',
    'Oil': '石油',
    ' Oil': ' 石油',
    ' Oil, ': ' 石油, ',
    'Plasma': '等离子体',
    ' Plasma': ' 等离子体',
    ' Plasma, ': ' 等离子体, ',
    'Metal': '金属',
    ' Metal': ' 金属',
    ' Metal, ': ' 金属, ',
    'Titanium': ' 钛',
    ' Titanium': ' 钛',
    ' Titanium, ': ' 钛, ',
    'Charcoal': '木炭',
    ' Charcoal': ' 木炭',
    ' Charcoal, ': ' 木炭, ',
    'Space': '太空',
    '	Hard Reset': '硬重置',
    '	Load': '加载',
    ' Company': ' 公司',
    ' Company ': ' 公司',
    'Convert ': '转换',
    'Convert': '转换',
    'Converting ': '转换',
    'Costs ': '花费 ',
    'Costs': '花费 ',
    'Big Bertha': '贝尔莎大炮',
    '/Sec': '/秒',
    ' Research': '研究',
    ' Resources': '资源',
    'Sol Center': '索尔中心',
    'Solar Panels': '太阳能板',
    'Solar System': '太阳系',
    'Ice Drill': '冰钻',
    'Igneous Extruder': '火成岩挤出机',
    'Lava Extractor': '熔岩提取器',
    ' Machines': '机器',
    'Magmatic Dynamo': '岩浆发电机',
    'Each Solar Panel produces ': '每个太阳能板生产 ',
    'Each engine produces': '每台发动机生产',
    'Earth Resources': '地球资源',
    'Electron Bath': '电子浴',
    'Empowered Blowtorch': '增压喷灯',
    'Gain ': '获取 ',
    'Get Advanced Drill': '获取 高级钻',
    'Get Annihilator': '获取 歼灭者',
    'Get Asteroid Destroyer': '获取 小行星驱逐舰',
    'Get Atomic Cannon': '获取 原子炮',
    'Get Battery': '获取 电池',
    'Get Battery T': '获取 T电池',
    'Get Big Bertha': '获取 贝尔莎大炮',
    'Get Biomass Infuser': '获取 生物质注入器',
    'Get Blowtorch': '获取 喷灯',
    'Get Caged Star': '获取 笼星',
    'Get Carbyne Drill': '获取 卡宾钻',
    'Get Charcoal Engine': '获取 木炭发动机',
    'Get Chronal Actuator': '获取 定向致动器',
    'Get Club': '获取 俱乐部',
    'Get Collector': '获取 收集器',
    'Get Crucible': '获取 坩埚',
    'Get Cubic Teleposer': '获取 集成电路电视',
    'Get Dead Werewolf Finder': '获取 死亡狼人探测器',
    'Get Death Star Jr': '获取 死星JR',
    'Get Desert Destroyer': '获取 沙漠驱逐舰',
    'Get Diamond Accretion Chamber': '获取 钻石吸积室',
    'Get Diamond Drill': '获取 金刚石钻',
    'Get Drone': '获取 无人机',
    'Get Electrolytic Cell': '获取 电解池',
    'Get Electron Bath': '获取 电子浴',
    'Get Explorer': '获取 探测器',
    'Get Extractor': '获取 提取器',
    'Get Forest Fryer': '获取 森林炸锅',
    'Get Fossilator': '获取 化石器',
    'Get Freezer': '获取 冰箱',
    'Get Furnace': '获取 熔炉',
    'Get Fusion Reactor': '获取 聚变反应堆',
    'Get Gas Giant Skimmer': '获取 巨型气体分离器',
    'Get Gem Miner': '获取 宝石矿工',
    'Get Giga Drill': '获取 千兆钻',
    'Get Grinder': '获取 磨床',
    'Get Heavy Drill': '获取 重型钻',
    'Get Hindenburg Excavation': '获取 兴登堡挖掘',
    'Get Hydrothermal Vent': '获取 水热排气',
    'Get Ice Drill': '获取 冰钻',
    'Get Ice Pickaxe': '获取 冰镐',
    'Get Igneous Extruder': '获取 火成岩挤出机',
    'Get Industrial Kiln': '获取 工业窑炉',
    'Get Interplanetary Laser': '获取 星际激光',
    'Get Interstellar Cow': '获取 星际牛',
    'Get Jupitonian Condensator': '获取 木星冷凝器',
    'Get Laser Cutter': '获取 激光切割机',
    'Get Low-Gravity Drill': '获取 ',
    'Get Lunarite Drill': '获取 月岩钻',
    'Get Magmatic Dynamo': '获取 岩浆发电机',
    'Get Magnet': '获取 磁铁',
    'Get Mass Deforester': '获取 大规模毁林者',
    'Get Meteorite Printer': '获取 陨石打印机',
    'Get Meteorite Web': '获取 陨石网',
    'Get meteorites the old-fashioned way: demolishing uninhabited exoplanets by firing high-energy particle beams at them, then collect the debris': '用老式的方法获取陨石：向其发射高能粒子束以摧毁无人系外行星，然后收集碎片',
    'Get Methane Power Station': '获取 甲烷发电站',
    'Get Microverse Pollutor': '获取 微宇宙探测器',
    'Get Miner': '获取 矿工',
    'Get Moon Cloner': '获取 月球克隆者',
    'Get Moon Quarry': '获取 月球采石场',
    'Get Moon Worker': '获取 月球工人',
    'Get Morphic Compressor': '获取 形态压缩机',
    'Get Mr Freeze': '获取 急冻人',
    'Get Multiverse Drill': '获取 多元宇宙钻',
    'Get Nebulous Synthesizer': '获取 星云合成器',
    'Get Nuclear Power Station': '获取 核电站',
    'Get Offshore Rig': '获取 海上钻机',
    'Get Oil Field': '获取 油田',
    'Get Overexchange Condenser': '获取 过度交换冷凝器',
    'Get Penta-Drill': '获取 五角钻',
    'Get Philosopher\'s Stone': '获取 魔法石',
    'Get Planet Smasher': '获取 行星粉碎机',
    'Get Planetary Excavator': '获取 行星挖掘机',
    'Get Planetary Nuclear Plant': '获取 行星核工厂',
    'Get Plasmatic Pit': '获取 等离子坑',
    'Get PSU': '获取 电源模块',
    'Get PSU T': '获取 T电源模块',
    'Get Pump': '获取 水泵',
    'Get Pumpjack': '获取 抽油机',
    'Get Quantum Drill': '获取 量子钻',
    'Get Rocket Droid': '获取 火箭机器人',
    'Get Russian Forest': '获取 俄罗斯森林',
    'Get Scout Ship': '获取 侦察船',
    'Get Seaside Scorcher': '获取 海边烤炉',
    'Get Solar Panel': '获取 太阳能板',
    'Get Space Cow': '获取 太空牛',
    'Get Star Harvester': '获取 星际收割机',
    'Get Suction Excavator': '获取 吸挖机',
    'Get Super-Heater': '获取 超级加热器',
    'Get T.A.R.D.I.S': '获取 塔迪斯',
    'Get Tanker': '获取 油船',
    'Get Titan-Drill': '获取 泰坦钻',
    'Get Uranium Enricher': '获取 铀浓缩器',
    'Get Vacuum Cleaner': '获取 真空吸尘器',
    'Get Volcanic Veluptuator': '获取 火山起伏器',
    'Get Woodburner': '获取 烧炭工',
    'Get Woodcutter': '获取 伐木工',
    'Get Yellowcake Recycler': '获取 黄饼回收器',
    'Giga Drill': '千兆钻',
    'Giga Drills extract Metal at colossal speeds': '千兆钻以极高的速度提取金属',
    'Grinder': '磨床',
    'Explorer': '探测器',
    'Exploration': '勘探',
    'Helium': '氦气',
    ' Helium': ' 氦气',
    ' Helium, ': ' 氦气, ',
    'Lunarite': '月岩',
    ' Lunarite': ' 月岩',
    ' Lunarite, ': ' 月岩, ',
    'Hydrogen': '氢气',
    ' Hydrogen': ' 氢气',
    ' Hydrogen, ': ' 氢气, ',
    'Meteorite': '陨石',
    ' Meteorite': ' 陨石',
    ' Meteorite, ': ' 陨石, ',
    'Methane': '甲烷',
    ' Methane': ' 甲烷',
    ' Methane, ': ' 甲烷, ',
    'Uranium': '铀',
    ' Uranium': ' 铀',
    ' Uranium, ': ' 铀, ',
    'Off': '关闭',
    ' Off': ' 关闭',
    ' More..': ' 更多...',
    ' Help / FAQ': ' 帮助 / FAQ',
    'Build': '建造',
    ' Gems per second': ' 宝石 每秒',
    ' Wood per second': ' 木头 每秒',
    ' wood per second': ' 木头 每秒',
    ' Metal per second': ' 金属 每秒',
    ' Charcoal per second': ' 木炭 每秒',
    ' Energy per second': ' 能源 每秒',
    'Offshore Rig': '海上钻机',
    'Penta-Drill': '五角钻',
    'Pluto': '冥王星',
    'Explore Moon': '探索月亮',
    'Explore Asteroid Belt': '探索小行星带',
    'Explore Jupiter': '探索木星',
    'Explore Kuiper Belt': '探索柯伊伯带',
    'Explore Mars': '探索火星',
    'Explore Pluto': '探索冥王星',
    'Explore Saturn': '探索土星',
    'Explore Sol Center': '探索索尔中心',
    'Explore The Wonder Station': '探索奇迹站',
    'Explore Venus': '探索金星',
    'full': '满',
    'Gem Miner': '宝石矿工',
    'Helium Tanker': '氦气运输船',
    'Not Built': '未建造',
    'Rocket': '火箭',
    'Saturn': '土星',
    'Scout Ship': '侦察船',
    'Neptune': '海王星',
    'Moon Quarry': '月球采石场',
    'Ocean Freezer': '海洋冷冻柜',
    'Oil Field': '油田',
    'Oil Fields are large open spaces, usually found in deserts where vast oil wells can be found under the ground': '油田是大型的露天场所，通常在沙漠中发现，在地下可以找到巨大的油井',
    'Offshore Rigs are megastructures floating in the oceans, extracting Oil from under the sea-beds': '海上钻机是漂浮在海洋中的巨型结构，从海床下开采石油',
    'Rocket Fuel': '火箭燃料',
    'Rocket fuel is created in chemical plants and is used to allow rockets to launch off into space and to travel to other planets and star systems': '火箭燃料是在化工厂中产生的，用于使火箭发射到太空并传播到其他行星和恒星系',
    'Small Pump': '小型泵',
    'Technologies': '技术',
    'The Moon': '月球',
    'The Moon is our largest satellite, revolving around the Earth once every 27 days. It contains a large quantity of Lunarite, left over from when it separated from the Earth billions of years ago. It is much stronger than regular metal and used to build more advanced machines': '月球是我们最大的卫星，每27天绕地球旋转一次。 它包含大量的月岩，是数十亿年前它与地球分离时留下的。 它比普通金属坚固得多，用于制造更先进的机器',
    'The Sol Scientific Center': '索尔科学中心',
    'The Super-Heater throws electricity at Hydrogen to turn it into a plasmatic substance': '这个超级加热器把电投向氢，把氢变成一种可塑物质',
    'Death Star Jr': '死星Jr',
    'David Guetta\'s Club': '大卫·库塔的俱乐部',
    'Cubic Teleposer': '集成电路电视',
    'Desert Destroyer': '沙漠驱逐舰',
    'Destroy Advanced Drill': '摧毁 高级钻',
    'Destroy Atomic Cannon': '摧毁 原子炮',
    'Destroy Beach Annihilator': '摧毁 海滩歼灭者',
    'Destroy Big Bertha': '摧毁 贝尔莎大炮',
    'Destroy Biomass Infuser': '摧毁 生物质注入器',
    'Destroy Caged Star': '摧毁 笼星',
    'Destroy Carbyne Drill': '摧毁 卡宾钻',
    'Destroy Charcoal Engine': '摧毁 木炭发动机',
    'Destroy Chemical Plant': '摧毁 化工厂',
    'Destroy Chronal Actuator': '摧毁 定向致动器',
    'Destroy Club': '摧毁 俱乐部',
    'Destroy Collector': '摧毁 收集者',
    'Destroy Cubic Teleposer': '摧毁 集成电路电视',
    'Destroy Dead Werewolf Finder': '摧毁 死亡狼人探测器',
    'Destroy Death Star Jr': '摧毁 死星Jr',
    'Destroy Desert Destroyer': '摧毁 沙漠驱逐舰',
    'Destroy Destroyer': '摧毁 驱逐舰',
    'Destroy Diamond Accretion Chamber': '摧毁 钻石吸积室',
    'Destroy Diamond Drill': '摧毁 金刚石钻',
    'Destroy Droid': '摧毁 机器人',
    'Destroy Electrolytic Cell': '摧毁 电解池',
    'Destroy Electron Bath': '摧毁 电子浴',
    'Destroy Empowered Blowtorch': '摧毁 增压喷灯',
    'Destroy Explorer': '摧毁 探测器',
    'Destroy Forest Fryer': '摧毁 森林炸锅',
    'Destroy Fossilator': '摧毁 化石器',
    'Destroy Furnace': '摧毁 熔炉',
    'Destroy Fusion Reactor': '摧毁 聚变反应堆',
    'Destroy Gas Giant Skimmer': '摧毁 巨型气体分离器',
    'Destroy Gaseous Magnet': '摧毁 气态磁铁',
    'Destroy Gem Miner': '摧毁 宝石矿工',
    'Destroy Giga Drill': '摧毁 千兆钻',
    'Destroy Grinder': '摧毁 磨床',
    'Destroy Heat Resistant Crucible': '摧毁 耐热坩埚',
    'Destroy Heavy Drill': '摧毁 重型钻',
    'Destroy Helium Drone': '摧毁 氦无人机',
    'Destroy Helium Tanker': '摧毁 氦气运输船',
    'Destroy Hindenburg Excavation': '摧毁 兴登堡发掘',
    'Destroy Hydrazine Catalyst': '摧毁 肼催化剂',
    'Destroy Hydrothermal Vent': '摧毁 水热排气',
    'Destroy Ice Drill': '摧毁 冰钻',
    'Destroy Ice Pickaxe': '摧毁 冰镐',
    'Destroy Igneous Extruder': '摧毁 火成岩挤出机',
    'Destroy Industrial Kiln': '摧毁 工业窑炉',
    'Destroy Interstellar Cow': '摧毁 星际牛',
    'Destroy Jupitonian Condensator': '摧毁 木星冷凝器',
    'Destroy Laser Cutter': '摧毁 激光切割机',
    'Destroy Lava Extractor': '摧毁 熔岩提取器',
    'Destroy Low-Gravity Drill': '摧毁 低重力钻',
    'Destroy Lunarite Drill': '摧毁 月岩钻',
    'Destroy Magmatic Dynamo': '摧毁 岩浆发电机',
    'Destroy Mass Deforester': '摧毁 大规模毁林者',
    'Destroy Meteorite Printer': '摧毁 陨石打印机',
    'Destroy Meteorite Web': '摧毁 陨石网',
    'Destroy Methane Station': '摧毁 甲烷站',
    'Destroy Microverse Pollutor': '摧毁 微宇宙探测器',
    'Destroy Miner': '摧毁 矿工',
    'Destroy Moon Cloner': '摧毁 月球克隆者',
    'Destroy Moon Quarry': '摧毁 月球采石场',
    'Destroy Morphic Compressor': '摧毁 形态压缩机',
    'Destroy Mr Freeze': '摧毁 急冻人',
    'Destroy Multiverse Drill': '摧毁 多元宇宙钻',
    'Destroy Nebulous Synthesizer': '摧毁 星云合成器',
    'Destroy Nuclear Station': '摧毁 核电站',
    'Destroy Ocean Freezer': '摧毁 海洋冰柜',
    'Destroy Offshore Rig': '摧毁 海上钻机',
    'Destroy Oil Field': '摧毁 油田',
    'Destroy Overexchange Condenser': '摧毁 过度交换冷凝器',
    'Destroy Oxidisation Chamber': '摧毁 氧化室',
    'Destroy Penta-Drill': '摧毁 五角钻',
    'Destroy Philosopher\'s Stone': '摧毁 魔法石',
    'Destroy Planet Smasher': '摧毁 行星粉碎机',
    'Destroy Planetary Excavator': '摧毁 行星挖掘机',
    'Destroy Planetary Nuclear Plant': '摧毁 行星核工厂',
    'Destroy Plasmatic Pit': '摧毁 等离子坑',
    'Destroy Pumpjack': '摧毁 抽油机',
    'Destroy Quantum Drill': '摧毁 量子钻',
    'Destroy Russian Forest': '摧毁 俄罗斯森林',
    'Destroy Scorcher': '摧毁 海边烤炉',
    'Destroy Scout': '摧毁 侦查兵',
    'Destroy Small Pump': '摧毁 小型泵',
    'Destroy Solar Panel': '摧毁 太阳能电池板',
    'Destroy Space Cow': '摧毁 太空牛',
    'Destroy Space Laser': '摧毁 太空激光',
    'Destroy Star Harvester': '摧毁 星际收割机',
    'Destroy Suction Excavator': '摧毁 吸挖机',
    'Destroy Super-Heater': '摧毁 超级加热器',
    'Destroy T.A.R.D.I.S': '摧毁 塔迪斯',
    'Destroy Titan-Drill': '摧毁 泰坦钻',
    'Destroy Uranium Enricher': '摧毁 铀浓缩器',
    'Destroy Vacuum Cleaner': '摧毁 真空吸尘器',
    'Destroy Volcanic Veluptuator': '摧毁 火山起伏器',
    'Destroy Woodburner': '摧毁 烧炭工',
    'Destroy Woodcutter': '摧毁 伐木工',
    'Destroy Yellowcake Recycler': '摧毁 黄饼回收器',
    'Diamond Accretion Chamber': '钻石吸积室',
    'Diamond Encrusted Drill': '镶钻钻',
    'Space Cow Plantation': '太空牛种植园',
    'Space Rocket': '宇宙火箭',
    'Space Scientific Satellite Station': '空间科学卫星站',
    'Speeds up time through quantum physics in order to produce even more Gold': '通过量子物理学加快时间以生产更多金',
    'Somehow, it works': '不知何故，它起作用了',
    'Star Harvester': '星际收割机',
    'Stargate': '星际之门',
    'Super-Heater': '超级加热器',
    'Technological Wonder': '技术奇迹',
    'Science Production': '科学生产',
    'Donate Resources': '捐赠资源',
    'Dormant': '休眠',
    'Drill of Titans': '泰坦钻',
    'Each engine produces ': '每个发动机生产 ',
    'Each one produces ': '每一个生产 ',
    'Mercury': '水星',
    'Mercury is a lifeless rock with little to no value. It is not worth exploring on the ground as there are no valuable materials present': '水星是一块没有生命的石头，几乎没有价值。因为没有珍贵的资料，所以不值得在地面上进行探索',
    'Meteorite Printer': '陨石打印机',
    'Energetic Wonder': '充满活力的奇迹',
    'Energy Deficit!': '能源短缺！',
    'Electrolytic Cell': '电解池',
    'Fire Moon Worker': '火月工人',
    'Forest Fryer': '森林炸锅',
    'Forests? What forests?': '森林?什么森林?',
    'Fossilator': '化石器',
    'Gas Giant Skimmer': '巨型气体分离器',
    'Ice Pickaxe': '冰镐',
    'Join our Discord!': '加入我们的 Discord!',
    'Jupiter': '木星',
    'Mars': '火星',
    'Mars is the second closest planet to Earth and is covered in red iron oxide, also called rust. You can find Titanium on the surface, but it is more common inside the crust. Titanium will allow for Methane power plants and Silicon production': '火星是离地球第二近的行星，覆盖着红色的氧化铁，也叫铁锈。你可以在表面找到钛，但在地壳内部更常见。钛将用于甲烷发电厂和硅的生产',
    'Metal is one of the primary resources. It is used for many things, including storage upgrades, machinery and most things in space': '金属是主要的资源之一。它被用于很多方面，包括存储升级、机器和太空中的大多数东西',
    'Lunarite Drill': '月岩钻',
    'Mass Deforester': '大规模毁林者',
    'Advanced Drill': '高级钻',
    'Activate Wonder': '激活奇迹',
    'Asteroid Belt': '小行星带',
    'Atomic Cannon': '原子炮',
    'Batteries': '电池',
    'Biomass Infuser': '生物质注入器',
    'Beach Annihilator': '海滩歼灭者',
    'Laser Cutter': '激光切割机',
    'The Rocket Wonder': '火箭奇迹',
    'The Precious Wonder': '珍贵奇迹',
    ' Ice and ': ' 冰 和 ',
    ' Charcoal and ': ' 木炭 和 ',
    ' Gold and ': ' 黄金 和 ',
    ' Silver and ': ' 银 和 ',
    'Upgrade Storage': '升级库存',
    ' Solar System': ' 太阳系',
    ' Sol Center': ' 索尔中心',
    'Turn Rocket Fuel ': '打开火箭燃料',
    'Upgrade your Charcoal storage size to ': '将您的 木炭 存储空间升级到 ',
    'Upgrade your gem storage size to ': '将您的 宝石 存储空间升级到 ',
    'Upgrade your Gold storage size to ': '将您的 黄金 存储空间升级到 ',
    'Upgrade your Helium storage size to ': '将您的 氦气 存储空间升级到 ',
    'Upgrade your Hydrogen storage size to ': '将您的 氢气 存储空间升级到 ',
    'Upgrade your Ice storage size to ': '将您的 冰 存储空间升级到 ',
    'Upgrade your Lava storage size to ': '将您的 岩浆 存储空间升级到 ',
    'Upgrade your Lunarite storage size to ': '将您的 月岩 存储空间升级到 ',
    'Upgrade your Meteorite storage size to ': '将您的 陨石 存储空间升级到 ',
    'Upgrade your Metal storage size to ': '将您的 金属 存储空间升级到 ',
    'Upgrade your methane storage size to ': '将您的 甲烷 存储空间升级到 ',
    'Upgrade your Oil storage size to ': '将您的 石油 存储空间升级到 ',
    'Upgrade your Silicon storage size to ': '将您的 硅 存储空间升级到 ',
    'Upgrade your silver storage size to ': '将您的 银 存储空间升级到 ',
    'Upgrade your Titanium storage size to ': '将您的 钛 存储空间升级到 ',
    'Upgrade your Uranium storage size to ': '将您的 铀 存储空间升级到 ',
    'Upgrade your wood storage size to ': '将您的 木头 存储空间升级到 ',
    'Uranium Enricher': '铀浓缩器',
    '	Costs': ' 花费',
    'Vacuum Cleaner': '真空吸尘器',
    'Woodburner': '烧炭工',
    'Woodcutter': '伐木工',
    'Antimatter Wonder': '反物质奇迹',
    'Build Rocket': '建造火箭',
    'Caged Star': '笼星',
    'Carbyne Drill': '卡宾钻',
    'Charcoal Engine': '木炭发动机',
    'Chemical Plant': '化工厂',
    'Chemical plants are used to make rocket fuel automatically': '化工厂用于自动制造火箭燃料',
    'Charcoal is a secondary tier resource and is used by Engines to produce power for your company. 1 Charcoal is created by burning ': '木炭是次要资源，为发动机提供动力用来为您的公司发电。 生产 1木炭 需要燃烧',
    'Turn Charcoal Production ': '切换 木炭生产 ',
    'Turn Electron Bath ': '切换 电子浴 ',
    'Turn Electron Meteorite ': '切换 陨石生产 ',
    'University Laboratory': '大学实验室',
    'Unlock Plasma Research': '解锁等离子研究',
    'Unlock EMC Machine Research': '解锁EMC机器研究',
    'Uses': '消耗',
    'Uses ': '消耗 ',
    'Volcanic Veluptuator': '火山起伏器',
    'Wonder Station': '奇迹站',
    'Yellowcake Recycler': '黄饼回收器',
    'Wonder Station - Floor': '奇迹站 - 层',
    'Research': '研究',
    'Remaining energy': '剩余能量',
    'Remaining plasma': '剩余等离子体',
    'Rocket Droid': '火箭机器人',
    'Rocket Wonder': '火箭奇迹',
    'Russian Forest': '俄罗斯森林',
    'Seaside Scorcher': '海边烤炉',
    'Storage Upgrade': '存储升级',
    'Quantum Drill': '量子钻',
    'Pumpjack': '抽油机',
    'Produces ': '生产 ',
    'Space Explorer': '宇宙探索',
    'Suction Excavator': '吸挖机',
    'Wood is one of the primary resources. It is used more often in early game for tools and buildings': '木材是主要资源之一。 在早期游戏中经常用于工具和建筑物',
    'Oil is pumped up from the ground and is used to build Tier 2 resource gatherers': '石油从地下开采出来，用于建造第二层资源采集者',
    'Outer Planetary Resources': '外行星资源',
    'Overexchange Condenser': '过度交换冷凝器',
    'Oxidisation Chamber': '氧化室',
    'Philosopher\'s Stone': '魔法石',
    'Helium Drone': '氦气无人机',
    'High School Science': '高中科学',
    'Hindenburg Excavation': '兴登堡挖掘',
    'Time remaining until ': '剩余时间,直到',
    ' storage': '存储',
    ' (Max. ': ' (上限 ',
    'Build an axe for your woodcutter': '为你的伐木工造一把斧头',
    'Build a small pump to extract Oil from the ground': '建一个小泵从地下抽油',
    'Build a small laboratory of your very own to start producing science': '建立一个你自己的小实验室，开始生产科学',
    'Build a shovel for your woodburner': '为你的烧炭人做一把铲子',
    'Build a pickaxe for your miner': '为你的矿工造一把矿镐',
    'Build a more effective laboratory to continue your quest into the realm of science at a significantly faster speed': '建立一个更有效的实验室，继续以更快的速度探索科学领域',
    'Build an even better version of the old laboratory to further your exploration of the realm of science': '在老实验室的基础上再建一个更好的版本，以促进你对科学领域的探索',
    'Build an improved pickaxe to mine Gems': '建造一个改良的挖掘宝石的镐子',
    'Build Chemical Plant': '建造 化工厂',
    'Build Dyson Section': '建造 戴森区',
    'Build Hydrazine Catalyst': '建造 肼催化剂',
    'Build Laboratory T': '建造 实验室 T',
    'Build Oxidisation Chamber': '建造 氧化室',
    'Energy is created by power sources such as steam engines, solar power and advances even to fusion power and nuclear energy. The maximum you can hold to start with is 100,000 Energy, but batteries are unlockable which can increase this': '能源是由蒸汽机、太阳能等能源产生的，甚至在核聚变和核能方面也有进步。一开始你最多可以储存100,000的能源，但是电池是可开启的，这就会增加能源',
    'Cost (Energy': '消耗 (能源',
    'Burns Charcoal to produce a steady source of Energy': '燃烧木炭产生稳定的能源来源',
    'Toggle All Energy Production + Consumption': '切换所有能源生产+消耗',
    ' Energy and uses 1 Charcoal per second': '能源和消耗 1木炭 每秒',
    'Gains Energy slowly from the sun without using any resources': '在不使用任何资源的情况下缓慢地从太阳获得能源',
    'Gaseous Magnet': '气态磁铁',
    ' Wonders': ' 奇迹',
    'Earth': '地球',
    'Earth Machines': '地球机器',
    'Energy Machines': '能源机器',
    'Dyson Segments': '戴森碎片',
    'Fat Free!': '不含脂肪！',
    'Furnace': '熔炉',
    'Fusion Reactor': '聚变反应堆',
    'Miner': '矿工',
    'Moon Cloner': '月球克隆者',
    'Multiverse Drill': '多元宇宙钻',
    'Outer Planets': '外行星',
    'Planet Smasher': '行星粉碎机',
    'Furnaces use electric heaters to produce heat to turn Wood into Charcoal. Because of the increased heat, the process is more efficient': '炉子使用电加热器产生热量，把木头变成木炭。因为增加了热量，这个过程更有效率',
    'Max': '最大',
    'Material': '材料',
    'Machine Name': '机器名称',
    'Manual Saving': '手动保存',
    'Meteorite Web': '陨石网',
    'Meteorite Wonder': '陨石奇迹',
    'Stats': '统计',
    'Sucks more than anything!': '吮吸比什么都重要！',
    'That\'s no moon! That\'s a Space Station! This cuts through asteroids to expose all of the Gold in the centers': '那不是月亮！ 那是空间站！ 这会切穿小行星以暴露中心的所有黄金',
    'Sucks in methane and cleans the planet at the same time!': '吸入甲烷并同时清洁地球！',
    'Rebuild Stargate': '重建星际之门',
    'Rebuild Stargate Wonder': '重建星际之门奇迹',
    'Rebuild Communication Wonder': '重建通讯奇迹',
    'Rebuild Antimatter Wonder': '重建反物质奇迹',
    'PSUs increase your plasma storage by 50,000 per PSU built': '每建造一个电源模块，你的等离子体存储将增加50000',
    'Laser Cutters slice trees (and fingers) more quickly than axes and produce a lot more wood': '激光切割机切割树木(和手指)的速度比斧子更快，产生更多的木材',
    'Kuiper Belt': '柯伊伯带',
    'Achievements': '成就',
    'Advanced Drills mine gem at mass. Because of the toughness of the drill needed it is slower than the heavy drill': '高级钻头大量开采宝石。由于所需要的钻头的韧性，它比重型钻头慢',
    'Auto Emc': '自动 Emc',
    'Base': '基础',
    'Auto-Save Duration': '自动保存时间',
    'Collapse Inner Solar System': '内太阳系坍缩',
    'Collapse Outer Solar System': '外太阳系坍缩',
    'Comms Wonder': '通讯奇迹',
    'Donating': '捐赠',
    'Export Save': '导出存档',
    'Heavy Drill': '重型钻',
    'Heavy Drills mine Metal at mass': '重型钻机大量开采金属',
    'Helium is the second most common element on gas giants such as Jupiter and Saturn': '氦是木星和土星等气态巨行星上第二常见的元素',
    'Home Science Kit': '家庭科学工具箱',
    'Import Save': '导入存档',
    'Import/Export': '导入/导出',
    'Saving': '保存',
    'Sol Scientific Center': '索尔科学中心',
    'The Antimatter Wonder': '反物质奇迹',
    'Themes': '主题',
    'Links': '链接',
    'Hard to handle and only found in volcanoes, Lava is one of the hardest resources to get': '熔岩很难处理，而且只存在于火山中，是最难获得的资源之一',
    'Heat Resistant Crucible': '耐热坩埚',
    'Graphics Options': '图形选项',
    'Screen Notifications': '屏幕通知',
    'Scientific Observatory': '科学观测台',
    'Short Name': '短名称',
    'Short Name (': '短名称 (',
    'Sidebar Height Compression (Not fully implemented)': '侧边栏高度压缩(未完全实现)',
    'Solar': '太阳',
    'Spacelab': '空间实验室',
    'Text Decoration': '文字装饰',
    'Notation': '符号',
    'You can enable settings to change the interface here': '您可以在此处启用设置以更改界面',
    'You can use a modified crucible to pick up lava and to store it for later use': '您可以使用改良的坩埚来拾取熔岩并将其存储以备后用',
    'You currently have ': '您目前有 ',
    'You shoot me down, but I won\'t fall. I am Titanium': '把射死了我，但我不会倒下。我是钛',
    'Copy and paste this onto a file somewhere so that you can import it into the game at a later date': '然后把它粘贴到某个文件上，这样你就可以在以后的游戏中导入它',
    'Copy Text Below To Clipboard': '将下面的文本复制到剪贴板',
    'Create an observatory to gaze upon the stars and acquire knowledge from them': '创建一个天文台来观察星星并从中获得知识',
    'Creating Meteorite is only possible from purer forms of energy than those created with earth technology. Therefore, Plasma is necessary to make the strong resource': '创造陨石只可能从更纯粹的形式的能源比那些与地球技术创造。因此，等离子体是制造强资源所必需的',
    'Creates Wood using old, useless materials found everywhere on Earth by crushing them and packing what remains as densely as possible until it can be used as Wood again': '利用地球上随处可见的旧的、无用的材料来制造木材，把它们压碎，然后把剩下的东西尽可能地打包，直到可以再次用作木材',
    'Cuts through asteroids to find silver deposits in their cores': '穿过小行星，在它们的核心找到银矿',
    'Current amount / Storage': '当前 数量/存储',
    'Dead Werewolf Finder': '死亡狼人探测器',
    'Hydrazine Catalyst': '肼催化剂',
    'Hide Completed Tabs': '隐藏已完成的选项卡',
    'I didn\'t like the intrusiveness of ads on this game and felt that getting people to pay for an in-game boost wouldn\'t bode well in the community as it makes the game feel like a freemium or pay-to-win game': '我不喜欢这款游戏中广告的干扰性，我觉得让人们为游戏中的刺激付费在社区中并不是个好兆头，因为这让游戏感觉像是一款免费增值或付费获胜的游戏',
    'I have a ': '我有一个',
    'Name': '名称',
    '	Save': '保存',
    '	Ring': '环',
    'Hidden': '隐藏',
    'Launch Rocket': '运行火箭',
    'Mr Freeze': '急冻人',
    'Native Moon Worker': '本地月球工人',
    'Paper': '纸',
    'Patreon Page': 'Patreon 页面',
    'PayPal Link': 'PayPal 链接',
    'Planetary Excavator': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    //    " ": "",
    ": ": "： ",
    "\n										": "",
    "\n								": "",
    "\n						": "",
    "\n		": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    //    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "\n": "",
    "\n	": "",
    "\n											": "",
    "\n										": "",
    "\n									": "",
    "\n								": "",
    "\n							": "",
    "\n					": "",
    "\n				": "",
    ",": ",",
    ".": ".",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Uses (.+) Energy and (.+) Hydrogen per second$/, '每秒消耗 $1 能源 和 $2 氢气'],
    [/^Uses (.+) Energy and (.+) Helium per second$/, '每秒消耗 $1 能源 和 $2 氦气'],
    [/^Uses (.+) Energy and (.+) Helium and (.+) Hydrogen per second$/, '每秒消耗 $1 能源 和 $2 氦气 和 $3 氢气'],
    [/^Uses (.+) Energy per second$/, '每秒消耗 $1 能量'],
    [/^Uses (.+) Wood per second$/, '每秒消耗 $1 木头'],
    [/^Uses (.+) wood per second$/, '每秒消耗 $1 木头'],
    [/^Produces (.+) Charcoal per second$/, '每秒生产 $1 木炭'],
    [/^Produces (.+) gem per second$/, '每秒生产 $1 宝石'],
    [/^Produces (.+) Gold per second$/, '每秒生产 $1 黄金'],
    [/^Produces (.+) Lunarite per second$/, '每秒生产 $1 月岩。'],
    [/^Produces (.+) Metal per second$/, '每秒生产 $1 金属'],
    [/^Produces (.+) methane per second$/, '每秒生产 $1 甲烷'],
    [/^Produces (.+) Oil per second$/, '每秒生产 $1 石油'],
    [/^Produces ([\d\.,]+) Plasma per second$/, '每秒生产 $1 等离子体'],
    [/^Produces (.+) Meteorite per second. Uses (.+) Plasma per second$/, '每秒生产 $1 陨石。每秒消耗 $2 等离子体'],
    [/^Produces (.+) silicon per second$/, '每秒生产 $1 硅'],
    [/^Produces (.+) Titanium per second$/, '每秒生产 $1 钛'],
    [/^Produces (.+) Uranium per second$/, '每秒生产 $1 铀'],
    [/^Produces (.+) wood per second$/, '每秒生产 $1 木头'],
    [/^Produces (.+) Helium per second$/, '每秒生产 $1 氦气'],
    [/^Produces (.+) Hydrogen per second$/, '每秒生产 $1 氢气'],
    [/^Produces (.+) Ice per second$/, '每秒生产 $1 冰'],
    [/^Produces (.+) silver per second$/, '每秒生产 $1 银'],
    [/^Produces (.+) Lava per second$/, '每秒生产 $1 岩浆'],
    [/^They produce (.+) Metal per second$/, '他们每秒生产 $1 金属。'],
    [/^They use (.+) Energy per second$/, '他们每秒消耗 $1 能源。'],
    [/^T(.+) Batteries$/, 'T$1 电池'],
    [/^ (.+) Seconds$/, ' $1 秒'],
    [/^ (.+) Minutes$/, ' $1 分钟'],
    [/^Each one produces (.+) science per second$/, '每一个每秒产生 $1 科学'],

]);
