/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Energy': '能源',
    ' Energy': ' 能源',
    ' Energy, ': ' 能源, ',
    'Gems': '宝石',
    ' Gems': ' 宝石',
    ' Gems, ': ' 宝石, ',
    'Gold': '黄金',
    ' Gold': ' 黄金',
    ' Gold, ': ' 黄金, ',
    'Ice': '冰',
    ' Ice': ' 冰',
    ' Ice, ': ' 冰, ',
    'Lava': '岩浆',
    ' Lava': ' 岩浆',
    ' Lava, ': ' 岩浆, ',
    'Silicon': '硅',
    ' Silicon': ' 硅',
    ' Silicon, ': ' 硅, ',
    'Silver': '银',
    ' Silver': ' 银',
    ' Silver, ': ' 银, ',
    'Wood': '木头',
    ' Wood': ' 木头',
    ' Wood, ': ' 木头, ',
    ' wood': ' 木头',
    ' wood, ': ' 木头, ',
    'Oil': '石油',
    ' Oil': ' 石油',
    ' Oil, ': ' 石油, ',
    'Plasma': '等离子体',
    ' Plasma': ' 等离子体',
    ' Plasma, ': ' 等离子体, ',
    'Metal': '金属',
    ' Metal': ' 金属',
    ' Metal, ': ' 金属, ',
    'Titanium': ' 钛',
    ' Titanium': ' 钛',
    ' Titanium, ': ' 钛, ',
    'Charcoal': '木炭',
    ' Charcoal': ' 木炭',
    ' Charcoal, ': ' 木炭, ',
    'Space': '太空',
    ' Company': ' 公司',
    'Convert': '转换',
    'Costs ': '花费 ',
    'Big Bertha': '贝尔莎大炮',
    '/Sec': '/秒',
    ' Research': '研究',
    ' Resources': '资源',
    'Sol Center': '索尔中心',
    'Solar Panels': '太阳能板',
    'Solar System': '太阳系',
    'Ice Drill': '冰钻',
    'Igneous Extruder': '火成岩挤出机',
    'Lava Extractor': '熔岩提取器',
    ' Machines': '机器',
    'Magmatic Dynamo': '岩浆发电机',
    'Each engine produces': '每台发动机生产',
    'Earth Resources': '地球资源',
    'Electron Bath': '电子浴',
    'Empowered Blowtorch': '增压喷灯',
    'Gain ': '获取 ',
    'Get Advanced Drill': '获取 高级钻',
    'Get Annihilator': '获取 歼灭者',
    'Get Asteroid Destroyer': '获取 小行星驱逐舰',
    'Get Atomic Cannon': '获取 原子炮',
    'Get Battery': '获取 电池',
    'Get Battery T': '获取 T电池',
    'Get Big Bertha': '获取 贝尔莎大炮',
    'Get Biomass Infuser': '获取 生物质注入器',
    'Get Blowtorch': '获取 喷灯',
    'Get Caged Star': '获取 笼星',
    'Get Carbyne Drill': '获取 卡宾钻',
    'Get Charcoal Engine': '获取 木炭发动机',
    'Get Chronal Actuator': '获取 定向致动器',
    'Get Club': '获取 俱乐部',
    'Get Collector': '获取 收集器',
    'Get Crucible': '获取 坩埚',
    'Get Cubic Teleposer': '获取 集成电路电视',
    'Get Dead Werewolf Finder': '获取 死亡狼人探测器',
    'Get Death Star Jr': '获取 死星JR',
    'Get Desert Destroyer': '获取 沙漠驱逐舰',
    'Get Diamond Accretion Chamber': '获取 钻石吸积室',
    'Get Diamond Drill': '获取 金刚石钻',
    'Get Drone': '获取 无人机',
    'Get Electrolytic Cell': '获取 电解池',
    'Get Electron Bath': '获取 电子浴',
    'Get Explorer': '获取 探测器',
    'Get Extractor': '获取 提取器',
    'Get Forest Fryer': '获取 森林炸锅',
    'Get Fossilator': '获取 化石器',
    'Get Freezer': '获取 冰箱',
    'Get Furnace': '获取 熔炉',
    'Get Fusion Reactor': '获取 聚变反应堆',
    'Get Gas Giant Skimmer': '获取 巨型气体分离器',
    'Get Gem Miner': '获取 宝石矿工',
    'Get Giga Drill': '获取 千兆钻',
    'Get Grinder': '获取 磨床',
    'Get Heavy Drill': '获取 重型钻',
    'Get Hindenburg Excavation': '获取 兴登堡挖掘',
    'Get Hydrothermal Vent': '获取 水热排气',
    'Get Ice Drill': '获取 冰钻',
    'Get Ice Pickaxe': '获取 冰镐',
    'Get Igneous Extruder': '获取 火成岩挤出机',
    'Get Industrial Kiln': '获取 工业窑炉',
    'Get Interplanetary Laser': '获取 星际激光',
    'Get Interstellar Cow': '获取 星际牛',
    'Get Jupitonian Condensator': '获取 木星冷凝器',
    'Get Laser Cutter': '获取 激光切割机',
    'Get Low-Gravity Drill': '获取 ',
    'Get Lunarite Drill': '获取 月岩钻',
    'Get Magmatic Dynamo': '获取 岩浆发电机',
    'Get Magnet': '获取 磁铁',
    'Get Mass Deforester': '获取 大规模毁林者',
    'Get Meteorite Printer': '获取 陨石打印机',
    'Get Meteorite Web': '获取 陨石网',
    'Get meteorites the old-fashioned way: demolishing uninhabited exoplanets by firing high-energy particle beams at them, then collect the debris': '用老式的方法获取陨石：向其发射高能粒子束以摧毁无人系外行星，然后收集碎片',
    'Get Methane Power Station': '获取 甲烷发电站',
    'Get Microverse Pollutor': '获取 微宇宙探测器',
    'Get Miner': '获取 矿工',
    'Get Moon Cloner': '获取 月球克隆者',
    'Get Moon Quarry': '获取 月球采石场',
    'Get Moon Worker': '获取 月球工人',
    'Get Morphic Compressor': '获取 形态压缩机',
    'Get Mr Freeze': '获取 急冻人',
    'Get Multiverse Drill': '获取 多元宇宙钻',
    'Get Nebulous Synthesizer': '获取 星云合成器',
    'Get Nuclear Power Station': '获取 核电站',
    'Get Offshore Rig': '获取 海上钻机',
    'Get Oil Field': '获取 油田',
    'Get Overexchange Condenser': '获取 过度交换冷凝器',
    'Get Penta-Drill': '获取 五角钻',
    'Get Philosopher\'s Stone': '获取 魔法石',
    'Get Planet Smasher': '获取 行星粉碎机',
    'Get Planetary Excavator': '获取 行星挖掘机',
    'Get Planetary Nuclear Plant': '获取 行星核工厂',
    'Get Plasmatic Pit': '获取 等离子坑',
    'Get PSU': '获取 电源模块',
    'Get PSU T': '获取 T电源模块',
    'Get Pump': '获取 水泵',
    'Get Pumpjack': '获取 抽油机',
    'Get Quantum Drill': '获取 量子钻',
    'Get Rocket Droid': '获取 火箭机器人',
    'Get Russian Forest': '获取 俄罗斯森林',
    'Get Scout Ship': '获取 侦察船',
    'Get Seaside Scorcher': '获取 海边烤炉',
    'Get Solar Panel': '获取 太阳能板',
    'Get Space Cow': '获取 太空牛',
    'Get Star Harvester': '获取 星际收割机',
    'Get Suction Excavator': '获取 吸挖机',
    'Get Super-Heater': '获取 超级加热器',
    'Get T.A.R.D.I.S': '获取 塔迪斯',
    'Get Tanker': '获取 油船',
    'Get Titan-Drill': '获取 泰坦钻',
    'Get Uranium Enricher': '获取 铀浓缩器',
    'Get Vacuum Cleaner': '获取 真空吸尘器',
    'Get Volcanic Veluptuator': '获取 火山起伏器',
    'Get Woodburner': '获取 烧炭工',
    'Get Woodcutter': '获取 伐木工',
    'Get Yellowcake Recycler': '获取 黄饼回收站',
    'Giga Drill': '千兆钻',
    'Giga Drills extract Metal at colossal speeds': '千兆钻以极高的速度提取金属',
    'Grinder': '磨床',
    'Explorer': '探测器',
    'Exploration': '勘探',
    'Helium': '氦气',
    ' Helium': ' 氦气',
    ' Helium, ': ' 氦气, ',
    'Lunarite': '月岩',
    ' Lunarite': ' 月岩',
    ' Lunarite, ': ' 月岩, ',
    'Hydrogen': '氢气',
    ' Hydrogen': ' 氢气',
    ' Hydrogen, ': ' 氢气, ',
    'Meteorite': '陨石',
    ' Meteorite': ' 陨石',
    ' Meteorite, ': ' 陨石, ',
    'Methane': '甲烷',
    ' Methane': ' 甲烷',
    ' Methane, ': ' 甲烷, ',
    'Uranium': '铀',
    ' Uranium': ' 铀',
    ' Uranium, ': ' 铀, ',
    'Off': '关闭',
    ' Help / FAQ': ' 帮助 / FAQ',
    'Build': '建造',
    ' Gems per second': ' 宝石每秒',
    ' Wood per second': ' 木头每秒',
    ' wood per second': ' 木头每秒',
    ' Metal per second': ' 金属每秒',
    'Offshore Rig': '海上钻机',
    'Penta-Drill': '五角钻',
    'Pluto': '冥王星',
    'Explore Moon': '探索月亮',
    'Explore Asteroid Belt': '探索小行星带',
    'Explore Jupiter': '探索木星',
    'Explore Kuiper Belt': '探索柯伊伯带',
    'Explore Mars': '探索火星',
    'Explore Pluto': '探索冥王星',
    'Explore Saturn': '探索土星',
    'Explore Sol Center': '探索索尔中心',
    'Explore The Wonder Station': '探索奇迹站',
    'Explore Venus': '探索金星',
    'full': '满',
    'Gem Miner': '宝石矿工',
    'Helium Tanker': '氦气运输船',
    'Not Built': '未建造',
    'Rocket': '火箭',
    'Saturn': '土星',
    'Scout Ship': '侦察船',
    'Neptune': '海王星',
    'Moon Quarry': '月球采石场',
    'Ocean Freezer': '海洋冷冻柜',
    'Oil Field': '油田',
    'Oil Fields are large open spaces, usually found in deserts where vast oil wells can be found under the ground': '油田是大型的露天场所，通常在沙漠中发现，在地下可以找到巨大的油井',
    'Offshore Rigs are megastructures floating in the oceans, extracting Oil from under the sea-beds': '海上钻机是漂浮在海洋中的巨型结构，从海床下开采石油',
    'Rocket Fuel': '火箭燃料',
    'Rocket fuel is created in chemical plants and is used to allow rockets to launch off into space and to travel to other planets and star systems': '火箭燃料是在化工厂中产生的，用于使火箭发射到太空并传播到其他行星和恒星系',
    'Small Pump': '小型泵',
    'Technologies': '科技',
    'The Moon': '月球',
    'The Moon is our largest satellite, revolving around the Earth once every 27 days. It contains a large quantity of Lunarite, left over from when it separated from the Earth billions of years ago. It is much stronger than regular metal and used to build more advanced machines': '月球是我们最大的卫星，每27天绕地球旋转一次。 它包含大量的月岩，是数十亿年前它与地球分离时留下的。 它比普通金属坚固得多，用于制造更先进的机器',
    'The Sol Scientific Center': '索尔科学中心',
    'The Super-Heater throws electricity at Hydrogen to turn it into a plasmatic substance': '这个超级加热器把电投向氢，把氢变成一种可塑物质',
    'Death Star Jr': '死星Jr',
    'David Guetta\'s Club': '大卫·库塔的俱乐部',
    'Cubic Teleposer': '集成电路电视',
    'Desert Destroyer': '沙漠驱逐舰',
    'Destroy Advanced Drill': '摧毁 高级钻',
    'Destroy Atomic Cannon': '摧毁 原子炮',
    'Destroy Beach Annihilator': '摧毁 海滩歼灭者',
    'Destroy Big Bertha': '摧毁 贝尔莎大炮',
    'Destroy Biomass Infuser': '摧毁 生物质注入器',
    'Destroy Caged Star': '摧毁 笼星',
    'Destroy Carbyne Drill': '摧毁 卡宾钻',
    'Destroy Charcoal Engine': '摧毁 木炭发动机',
    'Destroy Chemical Plant': '摧毁 化工厂',
    'Destroy Chronal Actuator': '摧毁 定向致动器',
    'Destroy Club': '摧毁 俱乐部',
    'Destroy Collector': '摧毁 收集者',
    'Destroy Cubic Teleposer': '摧毁 集成电路电视',
    'Destroy Dead Werewolf Finder': '摧毁 死亡狼人探测器',
    'Destroy Death Star Jr': '摧毁 死星Jr',
    'Destroy Desert Destroyer': '摧毁 沙漠驱逐舰',
    'Destroy Destroyer': '摧毁 驱逐舰',
    'Destroy Diamond Accretion Chamber': '摧毁 钻石吸积室',
    'Destroy Diamond Drill': '摧毁 金刚石钻',
    'Destroy Droid': '摧毁 机器人',
    'Destroy Electrolytic Cell': '摧毁 电解池',
    'Destroy Electron Bath': '摧毁 电子浴',
    'Destroy Empowered Blowtorch': '摧毁 增压喷灯',
    'Destroy Explorer': '摧毁 探测器',
    'Destroy Forest Fryer': '摧毁 森林炸锅',
    'Destroy Fossilator': '摧毁 化石器',
    'Destroy Furnace': '摧毁 熔炉',
    'Destroy Fusion Reactor': '摧毁 聚变反应堆',
    'Destroy Gas Giant Skimmer': '摧毁 巨型气体分离器',
    'Destroy Gaseous Magnet': '摧毁 气态磁铁',
    'Destroy Gem Miner': '摧毁 宝石矿工',
    'Destroy Giga Drill': '摧毁 千兆钻',
    'Destroy Grinder': '摧毁 磨床',
    'Destroy Heat Resistant Crucible': '摧毁 耐热坩埚',
    'Destroy Heavy Drill': '摧毁 重型钻',
    'Destroy Helium Drone': '摧毁 氦无人机',
    'Destroy Helium Tanker': '摧毁 氦气运输船',
    'Destroy Hindenburg Excavation': '摧毁 兴登堡发掘',
    'Destroy Hydrazine Catalyst': '摧毁 肼催化剂',
    'Destroy Hydrothermal Vent': '摧毁 水热排气',
    'Destroy Ice Drill': '摧毁 冰钻',
    'Destroy Ice Pickaxe': '摧毁 冰镐',
    'Destroy Igneous Extruder': '摧毁 火成岩挤出机',
    'Destroy Industrial Kiln': '摧毁 工业窑炉',
    'Destroy Interstellar Cow': '摧毁 星际牛',
    'Destroy Jupitonian Condensator': '摧毁 木星冷凝器',
    'Destroy Laser Cutter': '摧毁 激光切割机',
    'Destroy Lava Extractor': '摧毁 熔岩提取器',
    'Destroy Low-Gravity Drill': '摧毁 低重力钻',
    'Destroy Lunarite Drill': '摧毁 月岩钻',
    'Destroy Magmatic Dynamo': '摧毁 岩浆发电机',
    'Destroy Mass Deforester': '摧毁 大规模毁林者',
    'Destroy Meteorite Printer': '摧毁 陨石打印机',
    'Destroy Meteorite Web': '摧毁 陨石网',
    'Destroy Methane Station': '摧毁 甲烷站',
    'Destroy Microverse Pollutor': '摧毁 微宇宙探测器',
    'Destroy Miner': '摧毁 矿工',
    'Destroy Moon Cloner': '摧毁 月球克隆者',
    'Destroy Moon Quarry': '摧毁 月球采石场',
    'Destroy Morphic Compressor': '摧毁 形态压缩机',
    'Destroy Mr Freeze': '摧毁 急冻人',
    'Destroy Multiverse Drill': '摧毁 多元宇宙钻',
    'Destroy Nebulous Synthesizer': '摧毁 星云合成器',
    'Destroy Nuclear Station': '摧毁 核电站',
    'Destroy Ocean Freezer': '摧毁 海洋冰柜',
    'Destroy Offshore Rig': '摧毁 海上钻机',
    'Destroy Oil Field': '摧毁 油田',
    'Destroy Overexchange Condenser': '摧毁 过度交换冷凝器',
    'Destroy Oxidisation Chamber': '摧毁 氧化室',
    'Destroy Penta-Drill': '摧毁 五角钻',
    'Destroy Philosopher\'s Stone': '摧毁 魔法石',
    'Destroy Planet Smasher': '摧毁 行星粉碎机',
    'Destroy Planetary Excavator': '摧毁 行星挖掘机',
    'Destroy Planetary Nuclear Plant': '摧毁 行星核工厂',
    'Destroy Plasmatic Pit': '摧毁 等离子坑',
    'Destroy Pumpjack': '摧毁 抽油机',
    'Destroy Quantum Drill': '摧毁 量子钻',
    'Destroy Russian Forest': '摧毁 俄罗斯森林',
    'Destroy Scorcher': '摧毁 海边烤炉',
    'Destroy Scout': '摧毁 侦查兵',
    'Destroy Small Pump': '摧毁 小型泵',
    'Destroy Solar Panel': '摧毁 太阳能电池板',
    'Destroy Space Cow': '摧毁 太空牛',
    'Destroy Space Laser': '摧毁 太空激光',
    'Destroy Star Harvester': '摧毁 星际收割机',
    'Destroy Suction Excavator': '摧毁 吸挖机',
    'Destroy Super-Heater': '摧毁 超级加热器',
    'Destroy T.A.R.D.I.S': '摧毁 塔迪斯',
    'Destroy Titan-Drill': '摧毁 泰坦钻',
    'Destroy Uranium Enricher': '摧毁 铀浓缩器',
    'Destroy Vacuum Cleaner': '摧毁 真空吸尘器',
    'Destroy Volcanic Veluptuator': '摧毁 火山起伏器',
    'Destroy Woodburner': '摧毁 烧炭工',
    'Destroy Woodcutter': '摧毁 伐木工',
    'Destroy Yellowcake Recycler': '摧毁 黄饼回收站',
    'Diamond Accretion Chamber': '钻石吸积室',
    'Diamond Encrusted Drill': '镶钻钻',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    //    " ": "",
    ": ": "： ",
    "\n										": "",
    "\n								": "",
    "\n						": "",
    "\n		": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    //    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "\n": "",
    "\n	": "",
    "\n				": "",
    "\n					": "",
    "\n							": "",
    "\n								": "",
    "\n									": "",
    "\n										": "",
    ",": ",",
    ".": ".",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Uses (.+) Energy per second$/, '每秒消耗 $1 能量'],
    [/^Produces (.+) Charcoal per second$/, '每秒生产 $1 木炭'],
    [/^Produces (.+) gem per second$/, '每秒生产 $1 宝石'],
    [/^Produces (.+) Gold per second$/, '每秒生产 $1 黄金'],
    [/^Produces (.+) Lunarite per second$/, '每秒生产 $1 月岩。'],
    [/^Produces (.+) Metal per second$/, '每秒生产 $1 金属'],
    [/^Produces (.+) methane per second$/, '每秒生产 $1 甲烷'],
    [/^Produces (.+) Oil per second$/, '每秒生产 $1 石油'],
    [/^Produces (.+) Plasma per second$/, '每秒生产 $1 等离子体'],
    [/^Produces (.+) silicon per second$/, '每秒生产 $1 硅'],
    [/^Produces (.+) Titanium per second$/, '每秒生产 $1 钛'],
    [/^Produces (.+) Uranium per second$/, '每秒生产 $1 铀'],
    [/^Produces (.+) wood per second$/, '每秒生产 $1 木头'],
    [/^Produces (.+) Helium per second$/, '每秒生产 $1 氦气'],
    [/^Produces (.+) Hydrogen per second$/, '每秒生产 $1 氢气'],
    [/^Produces (.+) Ice per second$/, '每秒生产 $1 冰'],
    [/^Produces (.+) silver per second$/, '每秒生产 $1 银'],
    [/^Produces (.+) Lava per second$/, '每秒生产 $1 岩浆'],
    [/^They produce (.+) Metal per second$/, '他们每秒生产 $1 金属。'],
    [/^They use (.+) Energy per second$/, '他们每秒消耗 $1 能源。'],
    [/^T(.+) Batteries$/, 'T$1 电池'],

]);
